version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/Wholist"
    schedule:
      interval: "monthly"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"