changes | l10n/i18n:
  - "Wholist/Localization/Resources/**/*.resx"
  - "Wholist/Localization/Resources/**/*.Designer.cs"

changes | ci:
  - ".github/workflows/**/*"

changes | plugin:
  - "**/*.cs"
  - "**/*.csproj"
  - "**/packages.lock.json"

changes | docs:
  - "**/*.md"
  - "**/*.txt"
