files:
  - source: /Wholist/Resources/Localization/Strings.resx
    translation: /%original_path%/Strings.%two_letters_code%.resx
pull_request_title: 'Translation updates (Crowdin)'
commit_message: 'chore(l10n): translations updates for %original_file_name% (%language%) [skip ci]'
append_commit_message: 1
