name: "Tests"

on:
  push:
    branches: [main]
    paths:
      - "Wholist/**/*.cs"
      - "Wholist/**/*.csproj"
      - "Wholist/**/*.resx"
      - "Sirensong/**/*.cs"
  pull_request:
    branches: [main]
    paths:
      - "Wholist/**/*.cs"
      - "Wholist/**/*.csproj"
      - "Wholist/**/*.resx"
      - "Sirensong/**/*.cs"
    types: [ready_for_review, opened, synchronize, reopened]
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    env:
        DALAMUD_HOME: "/tmp/"
    strategy:
      fail-fast: false
      matrix:
        build_mode: ["Release", "Debug"]
        dalamud_version: ["latest", "stg/latest"]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x

      - name: Download Dalamud
        run: |
          wget https://goatcorp.github.io/dalamud-distrib/${{ matrix.dalamud_version }}.zip -O ${{ env.DALAMUD_HOME }}.zip
          unzip ${{ env.DALAMUD_HOME }}.zip -d ${{ env.DALAMUD_HOME }}

      - name: Check for Lint Errors
        id: lint
        working-directory: Wholist
        continue-on-error: true
        run: | 
          dotnet format --verify-no-changes > lint.txt 2>&1

      - name: Report Lint Errors
        working-directory: Wholist
        if : steps.lint.outcome == 'failure'
        run: |
          cat lint.txt | sed -E 's/^(.*)$/::warning:: \1/g'

      - name: Restore Project
        working-directory: Wholist
        run: dotnet restore

      - name: Build Project
        working-directory: Wholist
        run: | 
          dotnet build -c ${{ matrix.build_mode }}
          echo "Checksum: $(sha512sum bin/x64/${{ matrix.build_mode }}/Wholist.dll)"